// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cafeum;

#nullable disable

namespace cafeum.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20250410160717_Contact2")]
    partial class Contact2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cafeum.Modells.Kontaktmodell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeljesNev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Uzenet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kontakt");
                });

            modelBuilder.Entity("cafeum.Modells.Rendelesekmodell", b =>
                {
                    b.Property<int>("index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("mennyiseg")
                        .HasColumnType("int");

                    b.Property<int>("rendelesszam")
                        .HasColumnType("int");

                    b.Property<int>("termekId")
                        .HasColumnType("int");

                    b.Property<int>("vasarloId")
                        .HasColumnType("int");

                    b.HasKey("index");

                    b.HasIndex("termekId");

                    b.HasIndex("vasarloId");

                    b.ToTable("rendelesek");
                });

            modelBuilder.Entity("cafeum.Modells.Termekmodell", b =>
                {
                    b.Property<int>("termekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("termekAr")
                        .HasColumnType("int");

                    b.Property<int>("termekMeret")
                        .HasColumnType("int");

                    b.Property<string>("termekNev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("termekId");

                    b.ToTable("termek");
                });

            modelBuilder.Entity("cafeum.Modells.Vasarlokmodell", b =>
                {
                    b.Property<int>("vasarloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("vasarloCim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vasarloJelszo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vasarloMail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vasarloNev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("vasarloId");

                    b.ToTable("vasarlok");
                });

            modelBuilder.Entity("cafeum.Modells.Rendelesekmodell", b =>
                {
                    b.HasOne("cafeum.Modells.Termekmodell", "termekek")
                        .WithMany("termekek")
                        .HasForeignKey("termekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cafeum.Modells.Vasarlokmodell", "vasarlok")
                        .WithMany("vasarlok")
                        .HasForeignKey("vasarloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("termekek");

                    b.Navigation("vasarlok");
                });

            modelBuilder.Entity("cafeum.Modells.Termekmodell", b =>
                {
                    b.Navigation("termekek");
                });

            modelBuilder.Entity("cafeum.Modells.Vasarlokmodell", b =>
                {
                    b.Navigation("vasarlok");
                });
#pragma warning restore 612, 618
        }
    }
}
